In [2]:
import numpy as np
import tensorflow as tf

In [39]:
x = tf.constant([[1.0,2,3], [4,5,6]])
x

<tf.Tensor 'Const_8:0' shape=(2, 3) dtype=float32>

In [40]:
out = tf.exp(x - tf.reduce_max(x, axis=1, keepdims=True))
out

<tf.Tensor 'Exp_1:0' shape=(2, 3) dtype=float32>

In [42]:
out = out / tf.reduce_sum(out, axis=1, keepdims=True)

In [43]:
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(out))

[[1. 2. 3.]
 [4. 5. 6.]]
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]]
